# Generated by Django 3.0.5 on 2020-04-02 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foro', '0002_auto_20200402_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsetopic',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.CreateModel(
            name='ResponseToResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textResponse', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('parentResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.ResponseTopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
