# Generated by Django 3.0.5 on 2020-04-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0008_auto_20200404_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
