# Generated by Django 3.0.5 on 2020-04-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0009_auto_20200404_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.Profile'),
        ),
        migrations.AlterField(
            model_name='responsetoresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.Profile'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.Profile', verbose_name='Usuario'),
        ),
    ]
